using CKFoodMaker.Model;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CKFoodMaker.Resource
{
    public static class StaticResource
    {
        public static readonly JsonSerializerOptions SerializerOption = new()
        {
            Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
            NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals,
        };

        public static IReadOnlyCollection<Item> AllCookedBaseCategories { get; } =
        [
            new(9500, "CookedSoup", "スープ"),
            new(9501, "CookedPudding", "プリン"),
            new(9502, "CookedSalad", "サラダ"),
            new(9503, "CookedWrap", "ピーマンラップ"),
            new(9504, "CookedSteak", "ステーキ"),
            new(9505, "CookedCheese", "チーズ"),
            new(9506, "CookedDipSnack", "ディップスナック"),
            new(9507, "CookedSushi", "スシ"),
            new(9508, "CookedFishBalls", "つみれ"),
            new(9509, "CookedFillet", "フィレ"),
            new(9510, "CookedCereal", "シリアル"),
            new(9511, "CookedSmoothie", "スムージー"),
            new(9512, "CookedSandwich", "サンドイッチ"),
            new(9513, "CookedPanCurry", "カレー"),
            new(9514, "CookedCake", "ケーキ"),
        ];

        public static IReadOnlyCollection<Item> AllFoodMaterials { get; } =
        [
            new(1645,"LarvaMeat","幼虫肉"),
            new(1646,"GoldenLarvaMeat","金色の幼虫肉"),
            new(5500,"Mushroom","きのこ"),
            new(5502,"GiantMushroom2","ジャンボマッシュルーム"),
            new(5503,"AmberLarva2","幼虫の琥珀"),
            new(7901,"Meat","霜降り肉"),
            new(7902,"Egg","ドードーの卵"),
            new(8003,"HeartBerry","ハートベリー"),
            new(8006,"GlowingTulipFlower","発光チューリップ"),
            new(8009,"BombPepper","爆弾ピーマン"),
            new(8012,"Carrock","キャロック"),
            new(8015,"Puffungi","カビキノコ"),
            new(8024,"BloatOat","ボウチョウ麦"),
            new(8027,"Pewpaya","ピュパイヤ"),
            new(8030,"Pinegrapple","パイグラップル"),
            new(8033,"Grumpkin","ふきげんカボチャ"),
            new(8036,"Sunrice","サンライス"),
            new(8039,"Lunacorn","ルナコーン"),
            new(8100,"HeartBerryRare","金色のハートベリー"),
            new(8101,"GlowingTulipFlowerRare","金色の発光チューリップ"),
            new(8102,"BombPepperRare","金色の爆弾ピーマン"),
            new(8103,"CarrockRare","金色のキャロック"),
            new(8104,"PuffungiRare","金色のカビキノコ"),
            new(8105,"BloatOatRare","金色のボウチョウ麦"),
            new(8106,"PewpayaRare","金色のピュパイヤ"),
            new(8107,"PinegrappleRare","金色のパイグラップル"),
            new(8108,"GrumpkinRare","金色のふきげんガボチャ"),
            new(8109,"SunriceRare","金色のサンライス"),
            new(8110,"LunacornRare","金色のルナコーン"),
            new(9618,"AtlantianWormHeart","アトラスワームの心臓"),
            new(9700,"OrangeCaveGuppy","オレンジ色の洞窟グッピー"),
            new(9701,"BlueCaveGuppy","青色の洞窟グッピー"),
            new(9702,"RockJaw","ロックジョー"),
            new(9703,"GemCrab","宝石ガニ"),
            new(9704,"DaggerFin","カミソリウオ"),
            new(9705,"PinkPalaceFish","モモイロキュウデンギョ"),
            new(9706,"TealPalaceFish","アオミドリキュウデンギョ"),
            new(9707,"CrownSquid","大王イカ"),
            new(9708,"YellowBlisterHead","イエローブリスターヘッド"),
            new(9709,"GreenBlisterHead","緑色のブリスターヘッド"),
            new(9710,"DevilWorm","デビルワーム"),
            new(9711,"VampireEel","吸血ウナギ"),
            new(9712,"MoldShark","カビザメ"),
            new(9713,"RotFish","ロットフィッシュ"),
            new(9714,"BlackSteelUrchin","クロガネウニ"),
            new(9715,"AzureFeatherFish","空色のハネウオ"),
            new(9716,"EmeraldFeatherFish","翡翠色のハネウオ"),
            new(9717,"SpiritVeil","スピリットベール"),
            new(9718,"AstralJelly","星クラゲ"),
            new(9719,"BottomTracer","ボトムトレーサー"),
            new(9720,"SilverTorrentDart","銀色のダート"),
            new(9721,"GoldenTorrentDart","金色のダート"),
            new(9722,"PinkCoralotl","ピンクサンゴウオ"),
            new(9723,"WhiteCoralotl","シロサンゴウオ"),
            new(9724,"SolidSpikeback","ハードスパイクバック"),
            new(9725,"SandySpikeback","サンドスパイクバック"),
            new(9726,"GreyDuneTail","グレイデューンテール"),
            new(9727,"BrownDuneTail","ブラウンデューンテール"),
            new(9728,"TornisKingfish","トーニスキングフィッシュ"),
            new(9729,"DarkLavaEater","ダークラヴァイーター"),
            new(9730,"BrightLavaEater","ブライトラヴァイーター"),
            new(9731,"VerdantDragonfish","グリーンドラゴンフィッシュ"),
            new(9732,"ElderDragonfish","エルダードラゴンフィッシュ"),
            new(9733,"StarlightNautilus","スターライトノーチラス"),
            new(9734,"AngleFish","緑柱石のアングルフィッシュ"),
            new(9735,"Deepstalker","玲瓏なディープストーカー"),
            new(9736,"CosmicForm","宇宙の形状"),
            new(9737,"GoldenAngleFish","碧玉のアングルフィッシュ"),
            new(9738,"GoldenDeepstalker","華麗なディープストーカー"),
            new(9739,"TerraTrilobite","陸三葉虫"),
            new(9740,"LithoTrilobite","岩三葉虫"),
            new(9741,"PinkhornPico","ピンク角のピコ"),
            new(9742,"GreenhornPico","緑角のピコ"),
            new(9743,"RiftianLampfish","亀裂のランプフィッシュ"),
        ];

        public static IReadOnlyCollection<Item> ObsoleteFoodMaterials { get; } =
        [
            new(5501,"GiantMushroom2","ジャンボマッシュルーム(古)"),
            new(5607,"AmberLarva2","幼虫の琥珀(古)")
        ];

        public static IReadOnlyCollection<(int TalentId, string Name)> PetTalents =
        [
            (0, "近接攻撃スピード"),
            (1, "遠距離攻撃スピード"),
            (2, "クリティカルヒット確率"),
            (3, "クリティカルヒットダメージ"),
            (4, "物理近接ダメージ"),
            (5, "物理遠距離ダメージ"),
            (6, "ボスへの与ダメージ"),
            (7, "ヒット時にダメージが3倍になる確率"),
            (8, "ヒット時に燃焼ダメージ"),
            (9, "ヒットで敵の回復力を75%減少させる毒を与える確率"),
            (10, "近接ヒットで相手を気絶させる確率"),
            (11, "相手の移動スピードを4秒間8.0%低下させる"),
            (12, "光度"),
            (13, "青色の光度"),
            (14, "相手の気絶時間が増加"),
            (15, "気絶している相手へのダメージ"),
            (16, "移動スピード"),
            (17, "ヒット時に敵がすべりやすくなる確率"),
            (18, "相手の残り体力に応じてダメージが最大"),
            (19, "ヒット時に相手の燃焼効果を消費し即座に合計燃焼ダメージを与える確率"),
            (20, "1体の敵を発射物が貫通"),
            (21, "移動不可および気絶時間減少"),
            (22, "ヒット時にマナを得られる確率"),
        ];

        public static IReadOnlyDictionary<(PetType petType, PetColor color), string> PetColorDict
            = new Dictionary<(PetType petType, PetColor color), string>
        {
            { (PetType.PetDog,PetColor.Color_1) ,"茶" },
            { (PetType.PetDog,PetColor.Color_2) ,"白" },
            { (PetType.PetDog,PetColor.Color_3) ,"暗灰" },
            { (PetType.PetDog,PetColor.Color_4) ,"黄" },
            { (PetType.PetDog,PetColor.Color_5) ,"橙" },
            { (PetType.PetDog,PetColor.Color_6) ,"灰" },
            { (PetType.PetDog,PetColor.Color_7) ,"黒" },
            { (PetType.PetDog,PetColor.Color_8) ,"桃" },
            { (PetType.PetCat,PetColor.Color_1) ,"白" },
            { (PetType.PetCat,PetColor.Color_2) ,"黄" },
            { (PetType.PetCat,PetColor.Color_3) ,"桃" },
            { (PetType.PetCat,PetColor.Color_4) ,"橙" },
            { (PetType.PetCat,PetColor.Color_5) ,"紫" },
            { (PetType.PetCat,PetColor.Color_6) ,"灰" },
            { (PetType.PetCat,PetColor.Color_7) ,"青" },
            { (PetType.PetCat,PetColor.Color_8) ,"茶" },
            { (PetType.PetBird,PetColor.Color_1) ,"緑" },
            { (PetType.PetBird,PetColor.Color_2) ,"橙" },
            { (PetType.PetBird,PetColor.Color_3) ,"白" },
            { (PetType.PetBird,PetColor.Color_4) ,"紫" },
            { (PetType.PetBird,PetColor.Color_5) ,"青" },
            { (PetType.PetBird,PetColor.Color_6) ,"桃" },
            { (PetType.PetBird,PetColor.Color_7) ,"灰" },
            { (PetType.PetBird,PetColor.Color_8) ,"黄" },
            { (PetType.PetBunny,PetColor.Color_1) ,"白" },
            { (PetType.PetBunny,PetColor.Color_2) ,"卵" },
            { (PetType.PetBunny,PetColor.Color_3) ,"黄" },
            { (PetType.PetBunny,PetColor.Color_4) ,"灰" },
            { (PetType.PetBunny,PetColor.Color_5) ,"桃" },
            { (PetType.PetBunny,PetColor.Color_6) ,"黒" },
            { (PetType.PetBunny,PetColor.Color_7) ,"茶" },
            { (PetType.PetBunny,PetColor.Color_8) ,"橙" },
            { (PetType.PetMoth,PetColor.Color_1) ,"白" },
            { (PetType.PetMoth,PetColor.Color_2) ,"灰" },
            { (PetType.PetMoth,PetColor.Color_3) ,"茶" },
            { (PetType.PetMoth,PetColor.Color_4) ,"黄" },
            { (PetType.PetMoth,PetColor.Color_5) ,"青" },
            { (PetType.PetMoth,PetColor.Color_6) ,"緑" },
            { (PetType.PetMoth,PetColor.Color_7) ,"桃" },
            { (PetType.PetMoth,PetColor.Color_8) ,"卵" },
            { (PetType.PetTardigrade,PetColor.Color_1) ,"緑" },
            { (PetType.PetTardigrade,PetColor.Color_2) ,"青" },
            { (PetType.PetTardigrade,PetColor.Color_3) ,"灰" },
            { (PetType.PetTardigrade,PetColor.Color_4) ,"白" },
            { (PetType.PetTardigrade,PetColor.Color_5) ,"赤" },
            { (PetType.PetTardigrade,PetColor.Color_6) ,"黒" },
            { (PetType.PetTardigrade,PetColor.Color_7) ,"橙" },
            { (PetType.PetTardigrade,PetColor.Color_8) ,"桃" },
            { (PetType.PetSlimeBlob,PetColor.Color_1) ,"----" },
            { (PetType.PetSlipperySlimeBlob,PetColor.Color_1) ,"----" },
            { (PetType.PetPoisonSlimeBlob,PetColor.Color_1) ,"----" },
            { (PetType.PetLavaSlimeBlob,PetColor.Color_1) ,"----" },
            { (PetType.PetPrinceSlimeBlob,PetColor.Color_1) ,"----" },
        };
    }
}
